---

dist: trusty
sudo: true


matrix:
  include:

    - addons:
        postgresql: 9.3
        apt:
          packages:
            - postgresql-9.3-pgtap
      env:
        - POSTGRESQL=9.3

    - addons:
        postgresql: 9.4
        apt:
          packages:
            - postgresql-9.4-pgtap
      env:
        - POSTGRESQL=9.4

    - addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-9.5-pgtap
      env:
        - POSTGRESQL=9.5

    - addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-9.6-pgtap
      env:
        - POSTGRESQL=9.6

    - addons:
        postgresql: 10
        apt:
          packages:
            - postgresql-10-pgtap
      env:
        - POSTGRESQL=10


before_install:
  # These are needed to test debian package build
  - sudo apt-get install debhelper fakeroot
    postgresql-server-dev-all
    libtap-parser-sourcehandler-pgtap-perl

script:
  # Set PGPORT
  - export PGPORT=`pg_lsclusters ${POSTGRESQL} | grep ' online ' | tail -1 | awk '{print $3}'`
  # Test https://github.com/linz/postgresql-tableversion/issues/47
  - git tag -a "travis/1.2.3-4-gdeadbeef" -m "test"
  # Set and check PostgreSQL paths
  - export PATH=/usr/lib/postgresql/${POSTGRESQL}/bin:${PATH}
  - pg_config --version
  - psql --version
  - psql -c "select version()" template1
  # Build
  - make
  # Pre-install tests
  - make check
  # Pre-install tests
  - sudo env "PATH=$PATH" make install
  # Post-install tests
  - make installcheck
  - make installcheck-loader
  - make installcheck-loader-noext
  # Test upgrades from all tagged versions
  - sudo -u postgres createuser --superuser root
  - sudo env "PATH=$PATH" env "PGPORT=$PGPORT" test/ci/test_all_upgrades.sh
  # Test install from package
  - PG_SUPPORTED_VERSIONS=${POSTGRESQL} make deb
  - sudo env "PATH=$PATH" dpkg -i ../postgresql-${POSTGRESQL}-tableversion_*.deb

notifications:
  # LINZ corporate email server is dropping messages from Travis
  # see: https://github.com/linz/LI-tasks/issues/14
  email:
    - jeremy.palmer.nz@gmail.com
    - ivan.mincik@gmail.com

# vim: set ts=2 sts=2 sw=2 et:
