---
dist: bionic
sudo: true

env:
  matrix:
    - PG=10
    - PG=11
    - PG=12

before_install:
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common
    postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get update -qq
  - sudo apt-get install -y postgresql-${PG} postgresql-client-${PG} postgresql-${PG}-pgtap
    postgresql-server-dev-${PG} postgresql-server-dev-all debhelper fakeroot
    libtap-parser-sourcehandler-pgtap-perl

before_script:
  - sudo -u postgres createuser -s "$USER"
  - sudo -u postgres createuser -s root

script:
  # Set PATH as postgresql-server-dev-all pretends version is 11
  - export PATH=/usr/lib/postgresql/${PG}/bin:${PATH}
  # Test https://github.com/linz/postgresql-tableversion/issues/47
  - git tag -a "travis/1.2.3-4-gdeadbeef" -m "test"
  # Set and check PostgreSQL paths
  - pg_config --version
  - psql --version
  - psql -c "select version()" template1
  # Build
  - make
  # Pre-install tests
  - make check
  # Pre-install tests
  - sudo env "PATH=$PATH" make install
  # Post-install tests
  - make installcheck
  - make installcheck-loader
  - make installcheck-loader-noext
  # Test upgrades from all tagged versions
  - sudo env "PATH=$PATH" test/ci/test_all_upgrades.bash
  # Test install from package
  - PG_SUPPORTED_VERSIONS=${PG} make deb
  - sudo dpkg -i ../postgresql-${PG}-tableversion_*.deb
  - sudo dpkg -i ../tableversion_*.deb

notifications:
  # LINZ corporate email server is dropping messages from Travis
  # see: https://github.com/linz/LI-tasks/issues/14
  email:
    - jeremy.palmer.nz@gmail.com
    - ivan.mincik@gmail.com
# vim: set ts=2 sts=2 sw=2 et:
