---

dist: trusty
sudo: true


matrix:
  include:

    - addons:
        postgresql: 9.2
        apt:
          packages:
            - postgresql-9.2-pgtap
      env:
        - POSTGRESQL=9.2

    - addons:
        postgresql: 9.3
        apt:
          packages:
            - postgresql-9.3-pgtap
      env:
        - POSTGRESQL=9.3

    - addons:
        postgresql: 9.4
        apt:
          packages:
            - postgresql-9.4-pgtap
      env:
        - POSTGRESQL=9.4

    - addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-9.5-pgtap
      env:
        - POSTGRESQL=9.5

    - addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-9.6-pgtap
      env:
        - POSTGRESQL=9.6


before_install:
  # These are needed to test debian package build
  - sudo apt-get install debhelper fakeroot postgresql-server-dev-all

script:
  # Test https://github.com/linz/postgresql-tableversion/issues/47
  - git tag -a "travis/1.2.3-4-gdeadbeef" -m "test"
  - make
  - sudo env "PATH=$PATH" make install
  - PGPORT=5432 make installcheck || { cat regression.diffs; false; }
  # Test upgrades from all tagged versions
  - PGPORT=5432 test/ci/test_all_upgrades.sh
  - make deb
  # Test install from package
  - sudo env "PATH=$PATH" dpkg -i ../postgresql-${POSTGRESQL}-tableversion_*.deb


notifications:
  # LINZ corporate email server is dropping messages from Travis
  # see: https://github.com/linz/LI-tasks/issues/14
  email:
    - jeremy.palmer.nz@gmail.com
    - ivan.mincik@gmail.com

# vim: set ts=2 sts=2 sw=2 et:
