---

dist: trusty
sudo: true


matrix:
  include:

    - addons:
        postgresql: 9.2
        apt:
          packages:
            - postgresql-server-dev-9.2
            - postgresql-9.2-pgtap
      env:
        - POSTGRESQL=9.2

    - addons:
        postgresql: 9.3
        apt:
          packages:
            - postgresql-server-dev-9.3
            - postgresql-9.3-pgtap
      env:
        - POSTGRESQL=9.3

    - addons:
        postgresql: 9.4
        apt:
          packages:
            - postgresql-server-dev-9.4
            - postgresql-9.4-pgtap
      env:
        - POSTGRESQL=9.4

    - addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-server-dev-9.5
            - postgresql-9.5-pgtap
      env:
        - POSTGRESQL=9.5

    - addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-server-dev-9.6
            - postgresql-9.6-pgtap
      env:
        - POSTGRESQL=9.6


before_install:
  # These are needed to test debian package build
  - sudo apt-get install debhelper fakeroot

script:
  - make
  - sudo make install
  - PGPORT=5432 make installcheck || { cat regression.diffs; false; }
  # debian packaging is only available for PostgreSQL 9.3,
  # see https://github.com/linz/postgresql-tableversion/issues/27
  #
  # The -b switch is beacause only binary package works,
  # See https://github.com/linz/postgresql-tableversion/issues/29
  - if test $POSTGRESQL = 9.3; then dpkg-buildpackage -us -uc -b; fi
  # Now test upgrades from all tagged versions
  - test/ci/test_all_upgrades.sh


notifications:
  # LINZ corporate email server is dropping messages from Travis
  # see: https://github.com/linz/LI-tasks/issues/14
  email:
    - jeremy.palmer.nz@gmail.com
    - ivan.mincik@gmail.com

# vim: set ts=2 sts=2 sw=2 et:
